// GENERATED by scripts/build-media.mjs — do not edit by hand.
// Source of truth is the Categorized/ folder. Run `npm run media` to rebuild.
// Titles and descriptions live in lib/artworks.ts, keyed by these ids.

export type MediaKind = "image" | "gif" | "video";

export type MediaItem = {
  /** Stable id: "<category>/<slug>". Also the key used by lib/artworks.ts. */
  id: string;
  category: string;
  slug: string;
  kind: MediaKind;
  src: string;
  /** Set when the piece lives in a series subfolder, e.g. comic/ants. */
  series?: string;
  /** The series folder's name as written, for display. */
  seriesName?: string;
  /** Reading order within the series, from the file's numeric prefix. */
  order?: number;
  /** Still frame for animated GIFs, so a card can rest without animating. */
  poster?: string;
  width: number;
  height: number;
};

export const MEDIA: readonly MediaItem[] = [
  {
    "id": "animation/late-for-8-am",
    "category": "animation",
    "slug": "late-for-8-am",
    "kind": "video",
    "src": "/art/animation/late-for-8-am.mp4",
    "poster": "/art/animation/late-for-8-am-poster.webp",
    "width": 1080,
    "height": 608
  },
  {
    "id": "animation/still-more",
    "category": "animation",
    "slug": "still-more",
    "kind": "video",
    "src": "/art/animation/still-more.mp4",
    "poster": "/art/animation/still-more-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "animation/sunburst",
    "category": "animation",
    "slug": "sunburst",
    "kind": "video",
    "src": "/art/animation/sunburst.mp4",
    "poster": "/art/animation/sunburst-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "animation/the-hut",
    "category": "animation",
    "slug": "the-hut",
    "kind": "video",
    "src": "/art/animation/the-hut.mp4",
    "poster": "/art/animation/the-hut-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "comic/we-stay-prepared",
    "category": "comic",
    "slug": "we-stay-prepared",
    "kind": "image",
    "src": "/art/comic/we-stay-prepared.webp",
    "width": 1760,
    "height": 2200
  },
  {
    "id": "comic/ants-01-the-anthill",
    "category": "comic",
    "slug": "ants-01-the-anthill",
    "kind": "image",
    "src": "/art/comic/ants-01-the-anthill.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 1,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-02-impact",
    "category": "comic",
    "slug": "ants-02-impact",
    "kind": "image",
    "src": "/art/comic/ants-02-impact.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 2,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-03-the-colony",
    "category": "comic",
    "slug": "ants-03-the-colony",
    "kind": "image",
    "src": "/art/comic/ants-03-the-colony.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 3,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-04-ward",
    "category": "comic",
    "slug": "ants-04-ward",
    "kind": "image",
    "src": "/art/comic/ants-04-ward.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 4,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-05-ants",
    "category": "comic",
    "slug": "ants-05-ants",
    "kind": "image",
    "src": "/art/comic/ants-05-ants.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 5,
    "width": 1280,
    "height": 720
  },
  {
    "id": "custom/brainwave",
    "category": "custom",
    "slug": "brainwave",
    "kind": "image",
    "src": "/art/custom/brainwave.webp",
    "width": 1060,
    "height": 1500
  },
  {
    "id": "custom/car-14-livery",
    "category": "custom",
    "slug": "car-14-livery",
    "kind": "image",
    "src": "/art/custom/car-14-livery.webp",
    "width": 1833,
    "height": 2200
  },
  {
    "id": "custom/cat-nap",
    "category": "custom",
    "slug": "cat-nap",
    "kind": "image",
    "src": "/art/custom/cat-nap.webp",
    "width": 1833,
    "height": 2200
  },
  {
    "id": "custom/lemon",
    "category": "custom",
    "slug": "lemon",
    "kind": "image",
    "src": "/art/custom/lemon.webp",
    "width": 1000,
    "height": 1500
  },
  {
    "id": "custom/mayer-doa-studio",
    "category": "custom",
    "slug": "mayer-doa-studio",
    "kind": "image",
    "src": "/art/custom/mayer-doa-studio.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "custom/nimbu",
    "category": "custom",
    "slug": "nimbu",
    "kind": "image",
    "src": "/art/custom/nimbu.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "custom/rickshaw",
    "category": "custom",
    "slug": "rickshaw",
    "kind": "image",
    "src": "/art/custom/rickshaw.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "custom/sorting-unit",
    "category": "custom",
    "slug": "sorting-unit",
    "kind": "image",
    "src": "/art/custom/sorting-unit.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "game-characters/bazaar-boy",
    "category": "game-characters",
    "slug": "bazaar-boy",
    "kind": "image",
    "src": "/art/game-characters/bazaar-boy.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-cap",
    "category": "game-characters",
    "slug": "bazaar-npc-cap",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-cap.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-cap-bust",
    "category": "game-characters",
    "slug": "bazaar-npc-cap-bust",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-cap-bust.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-elder",
    "category": "game-characters",
    "slug": "bazaar-npc-elder",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-elder.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-elder-bust",
    "category": "game-characters",
    "slug": "bazaar-npc-elder-bust",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-elder-bust.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-tank",
    "category": "game-characters",
    "slug": "bazaar-npc-tank",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-tank.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazaar-npc-tank-bust",
    "category": "game-characters",
    "slug": "bazaar-npc-tank-bust",
    "kind": "image",
    "src": "/art/game-characters/bazaar-npc-tank-bust.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/blade-sprite",
    "category": "game-characters",
    "slug": "blade-sprite",
    "kind": "gif",
    "src": "/art/game-characters/blade-sprite.gif",
    "poster": "/art/game-characters/blade-sprite-poster.webp",
    "width": 640,
    "height": 640
  },
  {
    "id": "game-characters/grocers-stall",
    "category": "game-characters",
    "slug": "grocers-stall",
    "kind": "image",
    "src": "/art/game-characters/grocers-stall.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/jai-jai-store",
    "category": "game-characters",
    "slug": "jai-jai-store",
    "kind": "image",
    "src": "/art/game-characters/jai-jai-store.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/lead-bust",
    "category": "game-characters",
    "slug": "lead-bust",
    "kind": "image",
    "src": "/art/game-characters/lead-bust.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/lead-front",
    "category": "game-characters",
    "slug": "lead-front",
    "kind": "image",
    "src": "/art/game-characters/lead-front.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/model-sheet",
    "category": "game-characters",
    "slug": "model-sheet",
    "kind": "image",
    "src": "/art/game-characters/model-sheet.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "game-characters/pixel-sprite",
    "category": "game-characters",
    "slug": "pixel-sprite",
    "kind": "image",
    "src": "/art/game-characters/pixel-sprite.webp",
    "width": 640,
    "height": 640
  },
  {
    "id": "game-characters/shop-clerk-bob",
    "category": "game-characters",
    "slug": "shop-clerk-bob",
    "kind": "image",
    "src": "/art/game-characters/shop-clerk-bob.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/shop-clerk-bust",
    "category": "game-characters",
    "slug": "shop-clerk-bust",
    "kind": "image",
    "src": "/art/game-characters/shop-clerk-bust.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/shop-clerk-long-hair",
    "category": "game-characters",
    "slug": "shop-clerk-long-hair",
    "kind": "image",
    "src": "/art/game-characters/shop-clerk-long-hair.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/shop-npc-glasses",
    "category": "game-characters",
    "slug": "shop-npc-glasses",
    "kind": "image",
    "src": "/art/game-characters/shop-npc-glasses.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/spearbearer",
    "category": "game-characters",
    "slug": "spearbearer",
    "kind": "image",
    "src": "/art/game-characters/spearbearer.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "game-characters/starstruck",
    "category": "game-characters",
    "slug": "starstruck",
    "kind": "image",
    "src": "/art/game-characters/starstruck.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "game-characters/umbrella-cart",
    "category": "game-characters",
    "slug": "umbrella-cart",
    "kind": "image",
    "src": "/art/game-characters/umbrella-cart.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "my-avatars/tortilla",
    "category": "my-avatars",
    "slug": "tortilla",
    "kind": "image",
    "src": "/art/my-avatars/tortilla.webp",
    "width": 1080,
    "height": 1350
  },
  {
    "id": "portrait/coco",
    "category": "portrait",
    "slug": "coco",
    "kind": "image",
    "src": "/art/portrait/coco.webp",
    "width": 627,
    "height": 575
  },
  {
    "id": "portrait/cosmos",
    "category": "portrait",
    "slug": "cosmos",
    "kind": "image",
    "src": "/art/portrait/cosmos.webp",
    "width": 2200,
    "height": 2200
  },
  {
    "id": "portrait/smoke",
    "category": "portrait",
    "slug": "smoke",
    "kind": "image",
    "src": "/art/portrait/smoke.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "portrait/two-fish",
    "category": "portrait",
    "slug": "two-fish",
    "kind": "image",
    "src": "/art/portrait/two-fish.webp",
    "width": 1500,
    "height": 1075
  },
  {
    "id": "wallpaper/dnd",
    "category": "wallpaper",
    "slug": "dnd",
    "kind": "image",
    "src": "/art/wallpaper/dnd.webp",
    "width": 750,
    "height": 1334
  },
  {
    "id": "wallpaper/nahin",
    "category": "wallpaper",
    "slug": "nahin",
    "kind": "image",
    "src": "/art/wallpaper/nahin.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "wallpaper/nightie",
    "category": "wallpaper",
    "slug": "nightie",
    "kind": "image",
    "src": "/art/wallpaper/nightie.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "wallpaper/strike",
    "category": "wallpaper",
    "slug": "strike",
    "kind": "image",
    "src": "/art/wallpaper/strike.webp",
    "width": 1800,
    "height": 1800
  }
];

export const MEDIA_BY_ID: ReadonlyMap<string, MediaItem> = new Map(
  MEDIA.map((item) => [item.id, item]),
);

export const CATEGORIES = [
  "animation",
  "comic",
  "custom",
  "game-characters",
  "my-avatars",
  "portrait",
  "wallpaper"
] as const;

export type Category = (typeof CATEGORIES)[number];

export function mediaIn(category: string): readonly MediaItem[] {
  return MEDIA.filter((item) => item.category === category);
}

/** Pieces in one series, already in reading order. */
export function seriesPages(category: string, series: string): readonly MediaItem[] {
  return MEDIA.filter((m) => m.category === category && m.series === series);
}

/** Distinct series within a category, in the order they first appear. */
export function seriesIn(category: string): readonly { slug: string; name: string; pages: readonly MediaItem[] }[] {
  const out: { slug: string; name: string; pages: MediaItem[] }[] = [];
  for (const item of MEDIA) {
    if (item.category !== category || !item.series) continue;
    let row = out.find((s) => s.slug === item.series);
    if (!row) {
      row = { slug: item.series, name: item.seriesName ?? item.series, pages: [] };
      out.push(row);
    }
    row.pages.push(item);
  }
  return out;
}

export function media(id: string): MediaItem {
  const item = MEDIA_BY_ID.get(id);
  if (!item) throw new Error(`Unknown media id "${id}" — run \`npm run media\`.`);
  return item;
}
