// GENERATED by scripts/build-media.mjs — do not edit by hand.
// Source of truth is the Categorized/ folder. Run `npm run media` to rebuild.
// Titles and descriptions live in lib/artworks.ts, keyed by these ids.

export type MediaKind = "image" | "gif" | "video";

export type MediaItem = {
  /** Stable id: "<category>/<slug>". Also the key used by lib/artworks.ts. */
  id: string;
  category: string;
  slug: string;
  kind: MediaKind;
  src: string;
  /** Set when the piece lives in a series subfolder, e.g. comic/ants. */
  series?: string;
  /** The series folder's name as written, for display. */
  seriesName?: string;
  /** Reading order within the series, from the file's numeric prefix. */
  order?: number;
  /** Still frame for animated GIFs, so a card can rest without animating. */
  poster?: string;
  width: number;
  height: number;
};

export const MEDIA: readonly MediaItem[] = [
  {
    "id": "animation/animationn",
    "category": "animation",
    "slug": "animationn",
    "kind": "video",
    "src": "/art/animation/animationn.mp4",
    "poster": "/art/animation/animationn-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "animation/dooooorr1",
    "category": "animation",
    "slug": "dooooorr1",
    "kind": "video",
    "src": "/art/animation/dooooorr1.mp4",
    "poster": "/art/animation/dooooorr1-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "animation/kirbyyy",
    "category": "animation",
    "slug": "kirbyyy",
    "kind": "video",
    "src": "/art/animation/kirbyyy.mp4",
    "poster": "/art/animation/kirbyyy-poster.webp",
    "width": 1080,
    "height": 608
  },
  {
    "id": "animation/qweqeqeqeqe",
    "category": "animation",
    "slug": "qweqeqeqeqe",
    "kind": "video",
    "src": "/art/animation/qweqeqeqeqe.mp4",
    "poster": "/art/animation/qweqeqeqeqe-poster.webp",
    "width": 608,
    "height": 1080
  },
  {
    "id": "comic/your-paragraph-text",
    "category": "comic",
    "slug": "your-paragraph-text",
    "kind": "image",
    "src": "/art/comic/your-paragraph-text.webp",
    "width": 1760,
    "height": 2200
  },
  {
    "id": "comic/ants-01-document-0",
    "category": "comic",
    "slug": "ants-01-document-0",
    "kind": "image",
    "src": "/art/comic/ants-01-document-0.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 1,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-02-document-1",
    "category": "comic",
    "slug": "ants-02-document-1",
    "kind": "image",
    "src": "/art/comic/ants-02-document-1.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 2,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-03-ending-scene1",
    "category": "comic",
    "slug": "ants-03-ending-scene1",
    "kind": "image",
    "src": "/art/comic/ants-03-ending-scene1.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 3,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-04-ending-page-22",
    "category": "comic",
    "slug": "ants-04-ending-page-22",
    "kind": "image",
    "src": "/art/comic/ants-04-ending-page-22.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 4,
    "width": 1280,
    "height": 720
  },
  {
    "id": "comic/ants-05-ending-page-23",
    "category": "comic",
    "slug": "ants-05-ending-page-23",
    "kind": "image",
    "src": "/art/comic/ants-05-ending-page-23.webp",
    "series": "ants",
    "seriesName": "ants",
    "order": 5,
    "width": 1280,
    "height": 720
  },
  {
    "id": "custom/back",
    "category": "custom",
    "slug": "back",
    "kind": "image",
    "src": "/art/custom/back.webp",
    "width": 1833,
    "height": 2200
  },
  {
    "id": "custom/binn",
    "category": "custom",
    "slug": "binn",
    "kind": "image",
    "src": "/art/custom/binn.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "custom/brain",
    "category": "custom",
    "slug": "brain",
    "kind": "image",
    "src": "/art/custom/brain.webp",
    "width": 1060,
    "height": 1500
  },
  {
    "id": "custom/document-2",
    "category": "custom",
    "slug": "document-2",
    "kind": "image",
    "src": "/art/custom/document-2.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "custom/front-1",
    "category": "custom",
    "slug": "front-1",
    "kind": "image",
    "src": "/art/custom/front-1.webp",
    "width": 1833,
    "height": 2200
  },
  {
    "id": "custom/lemon",
    "category": "custom",
    "slug": "lemon",
    "kind": "image",
    "src": "/art/custom/lemon.webp",
    "width": 1000,
    "height": 1500
  },
  {
    "id": "custom/logo-final-istg-nimbu",
    "category": "custom",
    "slug": "logo-final-istg-nimbu",
    "kind": "image",
    "src": "/art/custom/logo-final-istg-nimbu.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "custom/logoo2",
    "category": "custom",
    "slug": "logoo2",
    "kind": "image",
    "src": "/art/custom/logoo2.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "game-characters/bazar-npc",
    "category": "game-characters",
    "slug": "bazar-npc",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazar-npc-bigframe",
    "category": "game-characters",
    "slug": "bazar-npc-bigframe",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc-bigframe.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazar-npc-bigframe2png",
    "category": "game-characters",
    "slug": "bazar-npc-bigframe2png",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc-bigframe2png.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazar-npc-bigframe3png",
    "category": "game-characters",
    "slug": "bazar-npc-bigframe3png",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc-bigframe3png.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazar-npc2",
    "category": "game-characters",
    "slug": "bazar-npc2",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc2.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/bazar-npc3",
    "category": "game-characters",
    "slug": "bazar-npc3",
    "kind": "image",
    "src": "/art/game-characters/bazar-npc3.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/blehh2",
    "category": "game-characters",
    "slug": "blehh2",
    "kind": "image",
    "src": "/art/game-characters/blehh2.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "game-characters/drmtwork",
    "category": "game-characters",
    "slug": "drmtwork",
    "kind": "image",
    "src": "/art/game-characters/drmtwork.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "game-characters/fff",
    "category": "game-characters",
    "slug": "fff",
    "kind": "image",
    "src": "/art/game-characters/fff.webp",
    "width": 1080,
    "height": 1920
  },
  {
    "id": "game-characters/illustration17",
    "category": "game-characters",
    "slug": "illustration17",
    "kind": "image",
    "src": "/art/game-characters/illustration17.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/illustration21",
    "category": "game-characters",
    "slug": "illustration21",
    "kind": "image",
    "src": "/art/game-characters/illustration21.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/illustration24",
    "category": "game-characters",
    "slug": "illustration24",
    "kind": "image",
    "src": "/art/game-characters/illustration24.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/illustration4",
    "category": "game-characters",
    "slug": "illustration4",
    "kind": "image",
    "src": "/art/game-characters/illustration4.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/main-charac-bigframe",
    "category": "game-characters",
    "slug": "main-charac-bigframe",
    "kind": "image",
    "src": "/art/game-characters/main-charac-bigframe.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/main-charac-front",
    "category": "game-characters",
    "slug": "main-charac-front",
    "kind": "image",
    "src": "/art/game-characters/main-charac-front.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/muhaha",
    "category": "game-characters",
    "slug": "muhaha",
    "kind": "gif",
    "src": "/art/game-characters/muhaha.gif",
    "poster": "/art/game-characters/muhaha-poster.webp",
    "width": 640,
    "height": 640
  },
  {
    "id": "game-characters/sprite-0004",
    "category": "game-characters",
    "slug": "sprite-0004",
    "kind": "image",
    "src": "/art/game-characters/sprite-0004.webp",
    "width": 640,
    "height": 640
  },
  {
    "id": "game-characters/supermarket-npc",
    "category": "game-characters",
    "slug": "supermarket-npc",
    "kind": "image",
    "src": "/art/game-characters/supermarket-npc.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/supermarket1",
    "category": "game-characters",
    "slug": "supermarket1",
    "kind": "image",
    "src": "/art/game-characters/supermarket1.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/supermarket2",
    "category": "game-characters",
    "slug": "supermarket2",
    "kind": "image",
    "src": "/art/game-characters/supermarket2.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "game-characters/supermart-bigframe",
    "category": "game-characters",
    "slug": "supermart-bigframe",
    "kind": "image",
    "src": "/art/game-characters/supermart-bigframe.webp",
    "width": 512,
    "height": 512
  },
  {
    "id": "my-avatars/tonniavatar",
    "category": "my-avatars",
    "slug": "tonniavatar",
    "kind": "image",
    "src": "/art/my-avatars/tonniavatar.webp",
    "width": 1080,
    "height": 1350
  },
  {
    "id": "portrait/cocoooo",
    "category": "portrait",
    "slug": "cocoooo",
    "kind": "image",
    "src": "/art/portrait/cocoooo.webp",
    "width": 627,
    "height": 575
  },
  {
    "id": "portrait/drimit",
    "category": "portrait",
    "slug": "drimit",
    "kind": "image",
    "src": "/art/portrait/drimit.webp",
    "width": 2200,
    "height": 2200
  },
  {
    "id": "portrait/fish",
    "category": "portrait",
    "slug": "fish",
    "kind": "image",
    "src": "/art/portrait/fish.webp",
    "width": 1500,
    "height": 1075
  },
  {
    "id": "portrait/new1-copy",
    "category": "portrait",
    "slug": "new1-copy",
    "kind": "image",
    "src": "/art/portrait/new1-copy.webp",
    "width": 1555,
    "height": 2200
  },
  {
    "id": "wallpaper/final111",
    "category": "wallpaper",
    "slug": "final111",
    "kind": "image",
    "src": "/art/wallpaper/final111.webp",
    "width": 1800,
    "height": 1800
  },
  {
    "id": "wallpaper/hbd",
    "category": "wallpaper",
    "slug": "hbd",
    "kind": "image",
    "src": "/art/wallpaper/hbd.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "wallpaper/nahinnn-1",
    "category": "wallpaper",
    "slug": "nahinnn-1",
    "kind": "image",
    "src": "/art/wallpaper/nahinnn-1.webp",
    "width": 1920,
    "height": 1080
  },
  {
    "id": "wallpaper/phone-wallpaper",
    "category": "wallpaper",
    "slug": "phone-wallpaper",
    "kind": "image",
    "src": "/art/wallpaper/phone-wallpaper.webp",
    "width": 750,
    "height": 1334
  }
];

export const MEDIA_BY_ID: ReadonlyMap<string, MediaItem> = new Map(
  MEDIA.map((item) => [item.id, item]),
);

export const CATEGORIES = [
  "animation",
  "comic",
  "custom",
  "game-characters",
  "my-avatars",
  "portrait",
  "wallpaper"
] as const;

export type Category = (typeof CATEGORIES)[number];

export function mediaIn(category: string): readonly MediaItem[] {
  return MEDIA.filter((item) => item.category === category);
}

/** Pieces in one series, already in reading order. */
export function seriesPages(category: string, series: string): readonly MediaItem[] {
  return MEDIA.filter((m) => m.category === category && m.series === series);
}

/** Distinct series within a category, in the order they first appear. */
export function seriesIn(category: string): readonly { slug: string; name: string; pages: readonly MediaItem[] }[] {
  const out: { slug: string; name: string; pages: MediaItem[] }[] = [];
  for (const item of MEDIA) {
    if (item.category !== category || !item.series) continue;
    let row = out.find((s) => s.slug === item.series);
    if (!row) {
      row = { slug: item.series, name: item.seriesName ?? item.series, pages: [] };
      out.push(row);
    }
    row.pages.push(item);
  }
  return out;
}

export function media(id: string): MediaItem {
  const item = MEDIA_BY_ID.get(id);
  if (!item) throw new Error(`Unknown media id "${id}" — run \`npm run media\`.`);
  return item;
}
